<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Total Recall

1. **Subsetting:** to extract a part of the list/ array
   
2. **Indexing:** to select individual elements of the list/ array

3. **Slicing:** to extract a part of the list/ array (functionally, it's subset of subsetting) by inputting (1) the start and end positions of the elements to be extracted, (2) the order in which the elements should be extracted (forward/ reverse)

4. **Masking:** selecting elements from a list/ array using a condition that is either true or false; elements that do not meet the condition will be returned as false, and therefore masked

# Show me the 'odd' letters

In [16]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

numbers = np_array_2d[:,0].astype(int)
isOdd = numbers % 2 == 1

print(np_array_2d[:, 1][isOdd])

['A' 'C' 'E' 'G' 'I']


# Numpy masking

In [29]:
array = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

#below 50
isTrue = array < 50
array[isTrue] = -1

#above 50
isTrue = array > 50
array[isTrue] = 1

#is 50
isTrue = array == 50
array[isTrue] = 0

print(array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
