<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [8]:
import numpy as np
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
#x = py_list  # OR
x = np_array
print(x)

print(x[0])
print(x[-1])

print(x[0:3])
print(x[1:6])

print(x[1:6:2])
print(x[:5])
print(x[:5])

print(x[5:2:-1])
print(x[::-1])

['a1' 'b2' 'c3' 'd4' 'e5' 'f6' 'g7' 'h8' 'i9' 'j10']
a1
j10
['a1' 'b2' 'c3']
['b2' 'c3' 'd4' 'e5' 'f6']
['b2' 'd4' 'f6']
['a1' 'b2' 'c3' 'd4' 'e5']
['a1' 'b2' 'c3' 'd4' 'e5']
['f6' 'e5' 'd4']
['j10' 'i9' 'h8' 'g7' 'f6' 'e5' 'd4' 'c3' 'b2' 'a1']


## 1.2 Arrays only | Subsetting by masking

In [13]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3

print(my_mask)
#need to convert my_mask into an np array before values can be displayed
print(np_array[my_mask])

np_array[np_array > 3]

[False False False  True  True  True  True  True  True  True]
[ 4  5  6  7  8  9 10]


array([ 4,  5,  6,  7,  8,  9, 10])

In [15]:
np_array[~(np_array > 3)]                 # '~' means 'NOT'

array([1, 2, 3])

In [16]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

In [17]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [20]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [22]:
print(py_list_2d[3])
np_array_2d[3]

[4, 'D']


array(['4', 'D'], dtype='<U21')

In [23]:
print(py_list_2d[3][0])
np_array_2d[3, 0]

4


np.str_('4')

In [24]:
print(py_list_2d[:3])
np_array_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]


array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [27]:
print(py_list_2d[:3][0]) 
#[:3] is considered a list; [0] outputs the 1st element of that list

np_array_2d[:3, 0]

[1, 'A']


array(['1', '2', '3'], dtype='<U21')

In [30]:
print(py_list_2d[3:6][0])
print(np_array_2d[3:6, 0])
print(np_array_2d[:, 0])

[4, 'D']
['4' '5' '6']
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


## 1.4 Growing lists

In [31]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [32]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
print(x)

x=[1]
x+= [2]
x+= [3]
x+= [4]
print(x)

x=[1]
x.append(2)
x.append(3)
x.append(4)
print(x)

[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]


In [34]:
x = [1, 2, 3]
x += [4, 5, 6]
print(x)

x=[1, 2, 3]
x.extend([4, 5, 6])
print(x)

#.append assumes the appended is ONE element
x=[1, 2, 3]
x.append([4, 5, 6])
print(x)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, [4, 5, 6]]


# Some loose ends

## 1.5 Tuples

In [37]:
a=(1, 2, 3)     # Define tuple
print(a[0])    # Access data

1


In [38]:
# The following will NOT work
a[0]=-1
a[0]+= [10]

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [40]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

print(x, y, z)

[1, 2, 3] [1, 2, 3] [1, 2, 3]


In [41]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

print(x, y, z)

[1, 2, 3] [1, 2, 3] [1, 2, 3]


## Footnotes